# Generated by Django 4.1.7 on 2023-04-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=25)),
                ('Last_name', models.CharField(max_length=25)),
                ('Photo', models.ImageField(upload_to='')),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
                ('Pin_code', models.IntegerField()),
                ('Sex', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('Mobile', models.IntegerField()),
                ('Mail_ID', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('Confirm_password', models.CharField(max_length=25)),
            ],
        ),
    ]
